/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as AuthenticatedRtePocRouteImport } from './routes/_authenticated/rte-poc'
import { Route as AuthenticatedLynxUsfmRouteImport } from './routes/_authenticated/lynx-usfm'
import { Route as AuthenticatedDebugRouteImport } from './routes/_authenticated/debug'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedViewBookIdChapterNumberRouteImport } from './routes/_authenticated/view/$bookId/$chapterNumber'
import { Route as AuthenticatedTranslationBookIdChapterNumberRouteImport } from './routes/_authenticated/translation/$bookId/$chapterNumber'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const AuthenticatedRtePocRoute = AuthenticatedRtePocRouteImport.update({
  id: '/rte-poc',
  path: '/rte-poc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLynxUsfmRoute = AuthenticatedLynxUsfmRouteImport.update({
  id: '/lynx-usfm',
  path: '/lynx-usfm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDebugRoute = AuthenticatedDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedViewBookIdChapterNumberRoute =
  AuthenticatedViewBookIdChapterNumberRouteImport.update({
    id: '/view/$bookId/$chapterNumber',
    path: '/view/$bookId/$chapterNumber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTranslationBookIdChapterNumberRoute =
  AuthenticatedTranslationBookIdChapterNumberRouteImport.update({
    id: '/translation/$bookId/$chapterNumber',
    path: '/translation/$bookId/$chapterNumber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/debug': typeof AuthenticatedDebugRoute
  '/lynx-usfm': typeof AuthenticatedLynxUsfmRoute
  '/rte-poc': typeof AuthenticatedRtePocRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/translation/$bookId/$chapterNumber': typeof AuthenticatedTranslationBookIdChapterNumberRoute
  '/view/$bookId/$chapterNumber': typeof AuthenticatedViewBookIdChapterNumberRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/debug': typeof AuthenticatedDebugRoute
  '/lynx-usfm': typeof AuthenticatedLynxUsfmRoute
  '/rte-poc': typeof AuthenticatedRtePocRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/': typeof AuthenticatedIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/translation/$bookId/$chapterNumber': typeof AuthenticatedTranslationBookIdChapterNumberRoute
  '/view/$bookId/$chapterNumber': typeof AuthenticatedViewBookIdChapterNumberRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/debug': typeof AuthenticatedDebugRoute
  '/_authenticated/lynx-usfm': typeof AuthenticatedLynxUsfmRoute
  '/_authenticated/rte-poc': typeof AuthenticatedRtePocRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/translation/$bookId/$chapterNumber': typeof AuthenticatedTranslationBookIdChapterNumberRoute
  '/_authenticated/view/$bookId/$chapterNumber': typeof AuthenticatedViewBookIdChapterNumberRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/legal'
    | '/login'
    | '/reset-password'
    | '/debug'
    | '/lynx-usfm'
    | '/rte-poc'
    | '/legal/privacy'
    | '/legal/terms'
    | '/projects/'
    | '/users/'
    | '/translation/$bookId/$chapterNumber'
    | '/view/$bookId/$chapterNumber'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/legal'
    | '/login'
    | '/reset-password'
    | '/debug'
    | '/lynx-usfm'
    | '/rte-poc'
    | '/legal/privacy'
    | '/legal/terms'
    | '/'
    | '/projects'
    | '/users'
    | '/translation/$bookId/$chapterNumber'
    | '/view/$bookId/$chapterNumber'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invitation'
    | '/legal'
    | '/login'
    | '/reset-password'
    | '/_authenticated/debug'
    | '/_authenticated/lynx-usfm'
    | '/_authenticated/rte-poc'
    | '/legal/privacy'
    | '/legal/terms'
    | '/_authenticated/'
    | '/_authenticated/projects/'
    | '/_authenticated/users/'
    | '/_authenticated/translation/$bookId/$chapterNumber'
    | '/_authenticated/view/$bookId/$chapterNumber'
    | '/_authenticated/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_authenticated/rte-poc': {
      id: '/_authenticated/rte-poc'
      path: '/rte-poc'
      fullPath: '/rte-poc'
      preLoaderRoute: typeof AuthenticatedRtePocRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lynx-usfm': {
      id: '/_authenticated/lynx-usfm'
      path: '/lynx-usfm'
      fullPath: '/lynx-usfm'
      preLoaderRoute: typeof AuthenticatedLynxUsfmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/debug': {
      id: '/_authenticated/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AuthenticatedDebugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/view/$bookId/$chapterNumber': {
      id: '/_authenticated/view/$bookId/$chapterNumber'
      path: '/view/$bookId/$chapterNumber'
      fullPath: '/view/$bookId/$chapterNumber'
      preLoaderRoute: typeof AuthenticatedViewBookIdChapterNumberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/translation/$bookId/$chapterNumber': {
      id: '/_authenticated/translation/$bookId/$chapterNumber'
      path: '/translation/$bookId/$chapterNumber'
      fullPath: '/translation/$bookId/$chapterNumber'
      preLoaderRoute: typeof AuthenticatedTranslationBookIdChapterNumberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDebugRoute: typeof AuthenticatedDebugRoute
  AuthenticatedLynxUsfmRoute: typeof AuthenticatedLynxUsfmRoute
  AuthenticatedRtePocRoute: typeof AuthenticatedRtePocRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedTranslationBookIdChapterNumberRoute: typeof AuthenticatedTranslationBookIdChapterNumberRoute
  AuthenticatedViewBookIdChapterNumberRoute: typeof AuthenticatedViewBookIdChapterNumberRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDebugRoute: AuthenticatedDebugRoute,
  AuthenticatedLynxUsfmRoute: AuthenticatedLynxUsfmRoute,
  AuthenticatedRtePocRoute: AuthenticatedRtePocRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedTranslationBookIdChapterNumberRoute:
    AuthenticatedTranslationBookIdChapterNumberRoute,
  AuthenticatedViewBookIdChapterNumberRoute:
    AuthenticatedViewBookIdChapterNumberRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LegalRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
